# Generated by Django 3.1.7 on 2021-02-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
